"""Build docs/ACCEPTANCE_REPORT.md from the recorded result files (acceptance, resources, daemon restart)."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
DOCS = ROOT / "docs"


def load(name: str) -> dict[str, Any]:
    p = DOCS / name
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else {}


def short(obj: Any, n: int = 600) -> str:
    text = json.dumps(obj, ensure_ascii=False, default=str)
    return (text[: n - 1] + "…") if len(text) > n else text


def main() -> None:
    acc = load("acceptance_results.json")
    res = load("resource_results.json")
    dmn = load("daemon_restart_results.json")
    lines = ["# Acceptance Report", "",
             "Generated by `scripts/acceptance/write_report.py` from the result files recorded by the acceptance harness "
             "(`run_acceptance.py`), `measure_resources.py` and `daemon_restart_check.py`. Machine and environment: "
             "[ENVIRONMENT.md](ENVIRONMENT.md). Models: Groq (free tier) first; when its per-minute or daily token limits "
             "run out, SCAR falls back to the local model (Qwen3-8B Q4_K_M in a SCAR-managed llama.cpp server), so "
             "some scenarios record `llamacpp/local`. Hand-written sections (`## Live …`) are kept when this file is "
             "regenerated.", "",
             "Status meanings: **VERIFIED** = exercised end-to-end on this machine with the evidence below; "
             "**IMPLEMENTED-UNVERIFIED** = complete and tested with doubles, live run blocked by the named prerequisite; "
             "**FAILED**.", "", "## D3 acceptance scenarios", "",
             "| # | Scenario | Status | Time | Evidence |", "|---|---|---|---|---|"]
    results = acc.get("results", {})
    for key in sorted(results, key=int):
        r = results[key]
        ev = dict(r.get("evidence", {}))
        ev.pop("traceback", None)
        extra = f" Prerequisite: {r['prerequisite']}." if r.get("prerequisite") else ""
        lines.append(f"| {key} | {r.get('name', '')} | **{r['status']}** | {r.get('seconds', '')} s | "
                     f"`{short(ev, 700).replace('|', '/')}`{extra} |")
    lines += ["", f"Sandbox of the last run: `{acc.get('sandbox', '')}`.", ""]
    if res:
        idle = res.get("idle", {})
        gpu = res.get("gpu", {})
        orph = res.get("orphans", {})
        bnd = res.get("bounded", {})
        rtg = res.get("routing", {})
        lines += ["## D4 resource acceptance", "", f"Measured {res.get('at', '')}.", "",
                  "| Requirement | Result | Pass |", "|---|---|---|",
                  f"| Idle CPU < ~2 % over {idle.get('seconds')} s (voice off, no tasks) | average "
                  f"{idle.get('avg_cpu_percent_of_machine')} % of the machine, max {idle.get('max_cpu_percent_of_machine')} % | "
                  f"{'yes' if idle.get('pass_cpu_below_2pct') else 'no'} |",
                  f"| Idle memory (documented) | RSS {idle.get('rss_mb')} MiB, {idle.get('threads')} threads, children: "
                  f"{idle.get('children') or 'none'} | — |",
                  f"| No continuous activity when idle | resource samples while idle: {idle.get('resource_samples_taken_while_idle')}; "
                  f"artifacts created: {idle.get('artifacts_created_while_idle')}; STT loaded: {idle.get('stt_loaded')}; "
                  f"embeddings loaded: {idle.get('embeddings_loaded')} | "
                  f"{'yes' if idle.get('resource_samples_taken_while_idle') == 0 and idle.get('artifacts_created_while_idle') == 0 and not idle.get('stt_loaded') else 'no'} |",
                  f"| No GPU memory held after idle timeout | VRAM {gpu.get('vram_mb_before')} → {gpu.get('vram_mb_while_loaded')} (loaded) → "
                  f"{gpu.get('vram_mb_after_idle')} MiB after idle; server PIDs alive after idle: {gpu.get('server_pids_alive_after_idle')} | "
                  f"{'yes' if gpu.get('pass_released') else gpu.get('skipped', 'no')} |",
                  f"| No leftover processes after completion/cancellation | children: {orph.get('children_after_complete_and_cancel')} | "
                  f"{'yes' if orph.get('pass_no_orphans') else 'no'} |",
                  f"| Bounded growth under stress | event queue after 100k events: {bnd.get('event_queue_after_100k')} (cap 256); "
                  f"fetch cache {bnd.get('fetch_cache_entries')}, search cache {bnd.get('search_cache_entries')} (caps 100/200) | "
                  f"{'yes' if bnd.get('pass_bounded') else 'no'} |",
                  f"| Cloud preferred; local only per policy | reasoning order: {' → '.join(rtg.get('reasoning_order', []))}; "
                  f"policy `{rtg.get('local_inference_policy')}` | {'yes' if rtg.get('local_after_cloud') else 'no'} |",
                  f"| Shutdown leaves nothing behind | {short(res.get('after_shutdown', {}), 200)} | "
                  f"{'yes' if not res.get('after_shutdown', {}).get('llama_server_running') else 'no'} |", ""]
    if dmn:
        lines += ["## Daemon restart (memory, scheduler, monitors, notifications)", "",
                  f"Status: **{dmn.get('status')}**", "", "```json", json.dumps({k: dmn.get(k) for k in (
                      "alias_persisted", "schedule", "monitor", "tasks", "missed_notifications")}, indent=2, default=str),
                  "```", ""]
    lines += ["## Audit notes (2026-09-27)", "",
              "The production-readiness audit ([AUDIT_LEDGER.md](../AUDIT_LEDGER.md)) found gaps these scenarios did not "
              "catch. All are fixed, with regression tests:", "",
              "* D3.2 ran inside a long-lived harness. From the real one-shot CLI, the page closed when the command "
              "exited (F-12).",
              "* D3.4 only checked that a phrase appeared in the reply. The reply was a raw OCR dump (F-11).",
              "* D3.9 passed with a scripted-looking path. The real-user wording \"inspect the failing tests, fix it, run "
              "the tests again\" stopped after the diagnosis and was still reported as verified success (F-07, F-08).", "",
              "## D5 security acceptance", "",
              "Verified by automated tests (see [testing.md](testing.md)); all pass on this machine:", "",
              "| Requirement | Tests |", "|---|---|",
              "| Model cannot bypass permissions | `tests/security/test_injection.py` (adversarial scripted model through every relevant tool, with session grants in place), `test_policy.py` |",
              "| External content cannot become instructions | injection corpus (web page, email, README, terminal output, OCR text, encoded PDF text) |",
              "| Destructive operations require authorization | `test_fs_pipeline.py`, `test_terminal.py`, `test_command_guard.py` |",
              "| Secrets never in logs/traces/model payloads/CLI/DB/child env | `test_secrets_and_isolation.py` |",
              "| Tests cannot perform dangerous real-world actions | sandbox fixtures + write guard (`conftest.py`), live-send guard tests (`test_comms_live_guard.py`) |",
              "| Communication actions validate recipients | `test_comms_pipeline.py`, `test_comms_contacts.py`, scope tests |",
              "| Filesystem boundaries hold against path tricks | `test_path_guard.py` (junction, symlink, UNC, ADS, case, 8.3, `\\\\?\\`, property tests) |",
              "| Every command has a timeout | `test_terminal.py::test_timeout_kills_tree`, pipeline timeout wrapper |",
              "| Runaway tasks/sub-agents cancellable; kill switch works | `test_agent.py::test_cancellation_mid_task`, `test_terminal.py::test_cancellation_kills_process`, kill-switch callbacks in runtime |",
              "| CRITICAL never auto-approved at any autonomy level | `test_policy.py::test_critical_never_auto_allowed` (hypothesis over levels × grant scopes) |", ""]
    out = DOCS / "ACCEPTANCE_REPORT.md"
    # live-session sections are written by hand; keep them
    old = out.read_text(encoding="utf-8") if out.exists() else ""
    if "\n## Live " in old:
        lines += [old[old.index("\n## Live "):].strip("\n"), ""]
    out.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print("wrote docs/ACCEPTANCE_REPORT.md")


if __name__ == "__main__":
    main()
